name: Rodar Scraper
on:
  schedule:
    - cron: '0 * * * *' # Roda de 1 em 1 hora
  workflow_dispatch: # Bot√£o para rodar manual
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: Rodar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
      - name: Salvar progresso
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ultima_noticia.txt
          git commit -m "Update news" || exit 0
          git push
